# 配置项目名和session的过期时间
server:
  servlet:
    context-path: /cloudDisk
    session:
      timeout: 600m
  tomcat:
    uri-encoding: UTF-8

# 配置OSS
aliyun:
  accessKeyId: *
  accessKeySecret: *
  endpoint: *
  bucketName: *
  urlPrefix: *

# 配置Mybatis
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  #  静态资源的访问路径
  mvc:
    static-path-pattern: /**
  datasource:
    # 配置数据源
    username: *
    password: *
    url: jdbc:mysql://localhost/cloudDisk?serverTimezone=Hongkong&useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver

    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000

  # RedisProperties
  redis:
    database: 11
    host: localhost
    port: 6379

  # 配置ThymeLeaf模板缓存
  thymeleaf:
    cache: true
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

  # 配置文件上传相关
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1024MB

  # KafkaProperties
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: *
      enable-auto-commit: true
      auto-commit-interval: 3000

# caffeine
caffeine:
  code:
    max-size: 10000
    expire-hours: 180
  markdown:
    max-size: 50000
    expire-hours: 180

#dubbo
dubbo:
  application:
    name: clouddisk
  registry:
    address: zookeeper://localhost:2181

clouddisk:
  maxShowSize: 40
  type: OSS


